version: '3'
services:
  app:
    # container_name: app-server
    # image: vesystem/vecloud-fpm:17.0
    # image: vesystem/vecloud:17.0
    image: vesystem/vecloud-fpm-alpine-full:17.0
    # image: nextcloud
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '9000'
    volumes:
      - nextcloud:/var/www/html
    networks:
      - vecloud
  nginx:
    # container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
    networks:
      - vecloud
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nextcloud:/var/www/html
  db:
    # container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - vecloud


networks:
  vecloud:
    driver: 'bridge'
volumes:
  mysql_data:
  nextcloud:
